



txt = 'research shows that preschool education plays an important part in preparing children for school. A recent longitudinal study in the Philippines has followed a cohort of 4,500 public elementary school students for 5 years. The study found that children who attended preschool consistently outperformed those who did not in literacy, mathematics and social-emotional skills. The Philippines Early Childhood Care and Development (ECCD) Longitudinal Study was funded by UNICEF, the Philippines Department of Education and the Australian Government. The research was conducted by the Australian Council for Educational Research (ACER) and involved case studies, student assessments and questionnaires completed by students, teachers and school leaders. The impact of preschool on learning at school. The aim of the study was to assess the impact of the introduction of the Kindergarten year into the Philippines’ K-12 Basic Education System. Data was collected at 6 points: at the start of Kindergarten, the end of Kindergarten and at the end of Grade 1, 2, 3 and 4. This study found preschool and day care made a positive difference to learning for the first 5 years,’ the report reads. ‘Even at the end of Grade 4, students who attended preschool and day care prior to attending Kindergarten outperformed those who did not in literacy, mathematics and social-emotional skills.” However, the authors caution that the quality of preschool teaching and learning remains unclear. “In the case studies, no mention was made of explicit teaching of social-emotional skills and general cognitive skills. These skills were an implied by-product of attending preschool and day care and interacting with other children,” they write.Social-emotional skills of children. A unique feature of the study was the measurement of students’ social-emotional skills, and the exploration of the relationship between social-emotional skills and literacy and mathematics achievement.“Social-emotional skills were measured as it is now well-known that children draw on a range of skills to succeed at school,” the researchers explain. “A child who can manage her emotions can use this skill when persisting on a mathematics task. Children who can recognise emotions in themselves and others, can use these skills to resolve a disagreement when working on a group project.”The study found that in general, children’s social-emotional skills were rated by teachers as medium to high. It was also clear that girls outperformed boys. As well as this, it was found that students’ social-emotional skills did not seem to develop over time, and those with high social-emotional skills outperformed students with medium or low social-emotional skills in literacy and mathematics. “Most students in this study are still learning to read at the end of Grade 4. '


txt = txt.replace('education','instruction').replace('children','young people' ).replace('students', 'people who attend school')



print(txt)


